name: pkg_dio
description: This package i explore every things about dio package.
version: 1.0.0
publish_to: "none"
resolution: workspace

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.1
  flutter_riverpod: ^3.2.1
  riverpod_annotation: ^4.0.2
  image_picker: ^1.2.1
  path_provider: ^2.1.5
  flutter_secure_storage: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  dart_code_linter: ^3.2.1
  build_runner: ^2.11.1
  riverpod_generator: ^4.0.3
