name: flutter_design_system
description: This package is a package for flutter design system exploration.
publish_to: "none"
version: 0.0.1
resolution: workspace

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
