import '../model/complex_args.dart' show ComplexArgs;
import '../router/app_router.gr.dart';
import 'package:flutter/material.dart';
import 'package:auto_route/auto_route.dart';

class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Column(
          children: [
            Text("Home Screen"),
            Wrap(
              crossAxisAlignment: WrapCrossAlignment.center,
              spacing: 8,
              children: [
                Icon(Icons.info, color: Colors.amber),
                Text("Home Screen route not generated by auto_route",style: Theme.of(context).textTheme.bodyMedium,),
              ],
            ),
          ],
        )

      ),
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [


              //==================== Set up navigation to ComplexArgumentsScreen ====================
              SizedBox(height: 16),
              TextButton.icon(
                onPressed: () => context.router.push(
                  ComplexArgumentsRoute(
                    args: ComplexArgs(
                      id: 42,
                      name: "The Answer",
                      tags: ["life", "universe", "everything"],
                    ),
                  ),
                ),
                label: const Text("Navigate to Complex Arguments Screen"),
                icon: const Icon(Icons.touch_app),
              ),


              //==================== Set up navigation to ReturnResultScreen ====================
              TextButton.icon(
                onPressed: ()async{
                  final result = await context.router.push(ReturnResultRoute());
                  if(result != null && context.mounted){
                    ScaffoldMessenger.of(context).showSnackBar(
                      SnackBar(content: Text("Received result: $result"))
                    );
                  }
                },
                label: const Text("Return result using pop"),
                icon: const Icon(Icons.ads_click),
              ),

              TextButton.icon(
                onPressed: (){
                  context.router.push(ReturnResultRoute(onResult: (result){
                      ScaffoldMessenger.of(context).showSnackBar(
                          SnackBar(content: Text("Received result: $result"))
                      );
                    }
                  ));
                },
                label: const Text("Return result using callback"),
                icon: const Icon(Icons.ac_unit),
              ),


              //==================== Set up navigation to NestedNavMainScreen ====================
              TextButton.icon(
                onPressed: ()=>context.router.push(NestedNavMainRoute()),
                label: const Text("Navigate to Nested Navigation Main Screen"),
                icon: const Icon(Icons.account_tree_sharp),
              ),

              //==================== Set up navigation to TabMainScreen ====================
              TextButton.icon(
                onPressed: ()=>context.router.push(TabMainRoute()),
                label: const Text("Navigate to Tab Main Screen"),
                icon: const Icon(Icons.tab),
              ),

              //==================== Set up navigation to AccountScreen ====================
              TextButton.icon(
                onPressed: ()=>context.router.push(AccountRoute()),
                label: const Text("Account Screen (protected by AuthGuard)"),
                icon: const Icon(Icons.account_circle),
              ),

              //==================== Set up navigation to AccountScreen ====================
              TextButton.icon(
                onPressed: ()=>context.router.push(CheckOutRoute()),
                label: const Text("Checkout Screen (manage by AuthGuard)"),
                icon: const Icon(Icons.account_circle),
              ),



            ],
          ),
        ),
      ),
    );
  }
}
