name: app
description: "A new Flutter project."
publish_to: "none"
resolution: workspace

version: 1.0.0+2

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storagex: ^0.0.1
  auto_router_x: ^0.0.1
  media_picker: ^0.0.1
  dio_x: ^0.0.1
  flutter_design_system: ^0.0.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
