name: app
description: "A new Flutter project."
publish_to: "none"
resolution: workspace

version: 1.0.0+2

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  pkg_flutter_secure_storage: ^1.0.0
  pkg_get_it: ^1.0.0
  pkg_go_router: ^1.0.0
  pkg_dio: ^1.0.0
  pkg_auto_router: ^1.0.0

  media_picker: ^0.0.1
  flutter_design_system: ^0.0.1
  cupertino_icons: ^1.0.8
  go_router_navigation: ^1.0.0
  clean_architecture_bloc: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
