name: go_router_navigation
description: This is a feature package, here we will implement go_router navigation.
publish_to: "none"
version: 1.0.0
resolution: workspace

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^17.0.1

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
